import Head from "next/head";
import React from "react";
import OverPercent from "./OverPercent";
import SEOApproach from "./SEOApproach";
import SEOBenefits from "./SEOBenefits";
import SeoFormBanner from "./SeoFormBanner";
import WhatSEO from "./WhatSEO";

const SeoService = () => {
  return (
    <>
      <Head>
        <title>Seo Service - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <SeoFormBanner />
        <OverPercent />
        <WhatSEO />
        <SEOBenefits />
        <SEOApproach />
      </main>
    </>
  );
};

export default SeoService;
