import Head from "next/head";
import React from "react";
import Navbar from "../components/shared/Navbar/Navbar";
import Footer from "./shared/Footer";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <div>
        <div maxWidth="1280px" m="auto">
          <header>
            <Navbar />
          </header>
        </div>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
};

export default Layout;
