import Head from "next/head";
import React from "react";
import AboutService from "../components/AboutService";
import AboutVonixu from "../components/AboutVonixu";
import BrandBanner from "../components/BrandBanner";
import ContactMe from "../components/ContactMe";
import OurValues from "../components/OurValues";
import TeamMember from "../components/TeamMember";
import Testimonials from "../components/Testimonials";

const About = () => {
  return (
    <>
      <Head>
        <title>About - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <AboutService />
        <AboutVonixu />
        <BrandBanner />
        <OurValues />
        <TeamMember/>
        <Testimonials />
        <ContactMe />
      </main>
    </>
  );
};

export default About;

