import Head from "next/head";
import React from "react";
import AboutVonixu from "../components/AboutVonixu";

const About = () => {
  return (
    <>
      <Head>
        <title>About - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24"> <AboutVonixu/> </main>
    </>
  );
};

export default About;

