import Head from "next/head";
import React from "react";

const About = () => {
  return (
    <>
      <Head>
        <title>About - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>About</main>
    </>
  );
};

export default About;

