import Head from "next/head";
import React from "react";
import Blog from "../components/Blog";

const agency = () => {
  return (
    <>
      <Head>
        <title>Agency - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <h1>hello agency</h1>
      </main>
    </>
  );
};

export default agency;
