import Head from "next/head";
import React from "react";
import AFullService from "../components/Agency/AFullService";
import Banner from "../components/Agency/Banner";
import Relationships from "../components/Agency/Relationships";

const agency = () => {
  return (
    <>
      <Head>
        <title>Agency - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <Banner/>
        <AFullService/>
        <Relationships/>
      </main>
    </>
  );
};

export default agency;
