import Head from "next/head";
import React from "react";
import AmazonSEOService from "../components/SEO/AmazonSEOService";

const amazonSeoService = () => {
  return (
    <>
      <Head>
        <title>Amazon SEO Service - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <AmazonSEOService />
      </main>
    </>
  );
};

export default amazonSeoService;
