import Head from "next/head";
import React from "react";
import BlogWritingService from "../components/DigitalMarketing/BlogWritingService";

const blogWritingService = () => {
  return (
    <>
      <Head>
        <title>blogWritingService - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <BlogWritingService />
      </main>
    </>
  );
};

export default blogWritingService;
