import Head from "next/head";
import React from "react";

const Carrier = () => {
  return (
    <>
      <Head>
        <title>Carrier - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Carrier</main>
    </>
  );
};

export default Carrier;
