import Head from "next/head";
import React from "react";
import BrandBanner from "../components/BrandBanner";
import ContactMe from "../components/ContactMe";
import Pricing from "../components/Pricing";
import WebConversation from "../components/WebConversation";
import WebDesignServices from "../components/webDesignServices";
import WebsiteInclude from "../components/WebsiteInclude";
import WhatMakeUs from "../components/WhatMakeUs";

const Carrier = () => {
  return (
    <>
      <Head>
        <title>Carrier - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <WebConversation />
        <WebDesignServices />
        <BrandBanner />
        <WebsiteInclude />
        <Pricing />
        <WhatMakeUs />
        <ContactMe />
      </main>
    </>
  );
};

export default Carrier;
