import Head from "next/head";
import React from "react";
import Entrepreneur from "../components/CEO/Entrepreneur";
import Established from "../components/CEO/Established";
import Experience from "../components/CEO/Experience";
import FoundedSeoViser from "../components/CEO/FoundedSeoViser";
import FreelancingCareer from "../components/CEO/FreelancingCareer";
import SeoExpert from "../components/CEO/SeoExpert";
import SeoFun from "../components/CEO/SeoFun";
import StartedVonixu from "../components/CEO/StartedVonixu";
import FreeSession from "../components/FreeSession";
import CeoBanner from "../components/CeoBanner";

const ceo = () => {
  return (
    <>
      <Head>
        <title>CEO - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <CeoBanner />
        <div className="py-12 container">
          <div className="bg-cover seminar cursor-pointer bg-center bg-no-repeat"></div>
        </div>
        <SeoFun />
        <Experience />
        <Entrepreneur />
        <SeoExpert />
        <FreelancingCareer />
        <Established />
        <StartedVonixu />
        <FoundedSeoViser />
        <FreeSession />
      </main>
    </>
  );
};

export default ceo;
