import Head from "next/head";
import React from "react";
import Banner from "../components/CEO/banner";
import SeoFun from "../components/CEO/SeoFun";


const ceo = () => {
  return (
    <>
      <Head>
        <title>CEO - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <Banner/>
        <SeoFun/>
      </main>
    </>
  );
};

export default ceo;
