import Head from "next/head";
import React from "react";
import ContactMe from "../components/ContactMe";
import MeetUs from "../components/MeetUs";
import ScheduleMeeting from "../components/ScheduleMeeting";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <ScheduleMeeting />
        <MeetUs/>
        <ContactMe />
      </main>
    </>
  );
};

export default Contact;
