import Head from "next/head";
import React from "react";
import ContentWritingService from "../components/DigitalMarketing/ContentWritingService";


const contentWritingService = () => {
  return (
    <>
      <Head>
        <title>contentWritingService - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <ContentWritingService />
      </main>
    </>
  );
};

export default contentWritingService;
