import Head from "next/head";
import React from "react";
import ConvertFigmaToReact from "../components/WebDesign&Development/ConvertFigmaToReact";

const convertFigmaToReact = () => {
  return (
    <>
      <Head>
        <title>convertFigmaToReact - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <ConvertFigmaToReact />
      </main>
    </>
  );
};

export default convertFigmaToReact;
