import Head from "next/head";
import React from "react";
import CreativeDesignService from "../components/GraphicDesign/CreativeDesignService";


const creativeDesignService = () => {
  return (
    <>
      <Head>
        <title>creativeDesignService - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <CreativeDesignService />
      </main>
    </>
  );
};

export default creativeDesignService;
