import Head from "next/head";
import React from "react";
import DropshippingOptimizationService from "../components/SEO/DropshippingOptimizationService";

const dropshippingOptimizationService = () => {
  return (
    <>
      <Head>
        <title>Dropshipping Optimization Service - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <DropshippingOptimizationService />
      </main>
    </>
  );
};

export default dropshippingOptimizationService;
