import Head from "next/head";
import React from "react";
import DynamicWebsite from "../components/WebDesign&Development/DynamicWebsite";

const dynamicWebsite = () => {
  return (
    <>
      <Head>
        <title>dynamicWebsite - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <DynamicWebsite />
      </main>
    </>
  );
};

export default dynamicWebsite;
