import Head from "next/head";
import React from "react";
import ECommerceSEO from "../components/ECommerceSEO/ECommerceSEO";

const eCommerceSeo = () => {
  return (
    <>
      <Head>
        <title>eCommerceSeo - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
       <ECommerceSEO/>
      </main>
    </>
  );
};

export default eCommerceSeo;
