import Head from "next/head";
import React from "react";
import EcomPPCAdManagement from "../components/DigitalMarketing/EcomPPCAdManagement";


const ecomPPCAdManagement = () => {
  return (
    <>
      <Head>
        <title>ecomPPCAdManagement - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <EcomPPCAdManagement />
      </main>
    </>
  );
};

export default ecomPPCAdManagement;
