import Head from "next/head";
import React from "react";
import Blog from "../components/Blog";

const FAQs = () => {
  return (
    <>
      <Head>
        <title>FAQs - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <h2>hello f a q s</h2>
      </main>
    </>
  );
};

export default FAQs;
