import Head from "next/head";
import React from "react";
import GoogleAdsManagement from "../components/DigitalMarketing/GoogleAdsManagement";


const googleAdsManagement = () => {
  return (
    <>
      <Head>
        <title>googleAdsManagement - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <GoogleAdsManagement />
      </main>
    </>
  );
};

export default googleAdsManagement;
