import Head from "next/head";
import React from "react";
import ImagePostProduction from "../components/GraphicDesign/ImagePostProduction";


const imagePostProduction = () => {
  return (
    <>
      <Head>
        <title>imagePostProduction - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <ImagePostProduction />
      </main>
    </>
  );
};

export default imagePostProduction;
