import Head from "next/head";
import Banner from "../components/Banner";
import BrandBanner from "../components/BrandBanner";
import Featured from "../components/Featured";
import GrowBusiness from "../components/GrowBusiness";
import Footer from "../components/shared/Footer";
import Navbar from "../components/shared/Navbar";
import WhyVonixu from "../components/WhyVonixu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header>
        <Navbar />
      </header>

      <main className="relative pt-20">
        {/* all components */}
        <Banner/>
        <Featured/>
        <WhyVonixu/>
        <GrowBusiness/>
        <BrandBanner />
      </main>

      <footer>
        <Footer />

      </footer>
    </div>
  );
}
