import Head from "next/head";
import Footer from "../components/shared/Footer";
import Navbar from "../components/shared/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header>
        <Navbar />
      </header>

      <main>{/* main part */}</main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
