import Head from "next/head";
import React from "react";
import MERNStackDevelopment from "../components/WebDesign&Development/MERNStackDevelopment";

const mERNStackDevelopment = () => {
  return (
    <>
      <Head>
        <title>mERNStackDevelopment - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <MERNStackDevelopment />
      </main>
    </>
  );
};

export default mERNStackDevelopment;
