import Head from "next/head";
import React from "react";
import Blog from "../components/Blog";
import FreeSession from "../components/FreeSession";
import OurProcess from "../components/OurProcess";

const ourProcess = () => {
  return (
    <>
      <Head>
        <title>Our Process - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <OurProcess />
        <section className="mt-16">
          <FreeSession />
        </section>
      </main>
    </>
  );
};

export default ourProcess;
