import Head from "next/head";
import React from "react";
import Blog from "../components/Blog";

const ourProcess = () => {
  return (
    <>
      <Head>
        <title>Our Process - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <h3>hello our process</h3>
      </main>
    </>
  );
};

export default ourProcess;
