import Head from "next/head";
import React from "react";

const ourTeam = () => {
  return (
    <>
      <Head>
        <title>Our Team - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <h3>hello our team</h3>
      </main>
    </>
  );
};

export default ourTeam;
