import Head from "next/head";
import React from "react";
import MeetOurTeam from "../components/OurTeam/MeetOurTeam";
import TeamMember from "../components/TeamMember";

const ourTeam = () => {
  return (
    <>
      <Head>
        <title>Our Team - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <MeetOurTeam/>
        <TeamMember/>
      </main>
    </>
  );
};

export default ourTeam;
