import Head from "next/head";
import React from "react";
import ProductReviewWritingService from "../components/DigitalMarketing/ProductReviewWritingService";


const productReviewWritingService = () => {
  return (
    <>
      <Head>
        <title>productReviewWritingService - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <ProductReviewWritingService />
      </main>
    </>
  );
};

export default productReviewWritingService;
