import Head from "next/head";
import React from "react";
import RestaurantSEO from "../components/SEO/RestaurantSEO";

const restaurantSeo = () => {
  return (
    <>
      <Head>
        <title>Restaurant SEO - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <RestaurantSEO />
      </main>
    </>
  );
};

export default restaurantSeo;
