import Head from "next/head";
import React from "react";
import SEOforTravelAgency from "../components/SEO/SEOforTravelAgency";

const seoForTravelAgency = () => {
  return (
    <>
      <Head>
        <title>SEO For Travel Agency - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <SEOforTravelAgency />
      </main>
    </>
  );
};

export default seoForTravelAgency;
