import Head from "next/head";
import React from "react";
import OverPercent from "../components/ServicesComponents/OverPercent";
import SEOApproach from "../components/ServicesComponents/SEOApproach";
import SEOBenefits from "../components/ServicesComponents/SEOBenefits";
import SeoFormBanner from "../components/ServicesComponents/SeoFormBanner";
import Testimonials from "../components/ServicesComponents/Testimonials";
import WhatSEO from "../components/ServicesComponents/WhatSEO";

const seoServices = () => {
  return (
    <>
      <Head>
        <title>Services - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <SeoFormBanner />
        <OverPercent />
        <WhatSEO />
        <SEOBenefits />
        <SEOApproach />
        <Testimonials />
      </main>
    </>
  );
};

export default seoServices;
