import Head from "next/head";
import React from "react";
import ShopifySEOService from "../components/SEO/ShopifySEOService";

const shopifySeoService = () => {
  return (
    <>
      <Head>
        <title>Shopify SEO Service - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <ShopifySEOService />
      </main>
    </>
  );
};

export default shopifySeoService;
