import Head from "next/head";
import React from "react";
import SocialMediaContentCreation from "../components/DigitalMarketing/SocialMediaContentCreation";


const socialMediaContentCreation = () => {
  return (
    <>
      <Head>
        <title>socialMediaContentCreation - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <SocialMediaContentCreation />
      </main>
    </>
  );
};

export default socialMediaContentCreation;
