import Head from "next/head";
import React from "react";
import TotalBranding from "../components/TotalBranding/TotalBranding";

const totalBranding = () => {
  return (
    <>
      <Head>
        <title>totalBranding - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <TotalBranding />
      </main>
    </>
  );
};

export default totalBranding;
