import Head from 'next/head';
import React from 'react';
import WebDesignPortfolio from '../components/WebDesignPortfolio';

const webPortfolio = () => {
  return (
    <>
      <Head>
        <title>Portfolio - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

 <main className="relative pt-24">
   <WebDesignPortfolio/>
 </main>

    </>
  );
};

export default webPortfolio;