import Head from "next/head";
import React from "react";
import WebsiteDevelopmentService from "../components/WebDesign&Development/WebsiteDevelopmentService";

const websiteDevelopmentService = () => {
  return (
    <>
      <Head>
        <title>websiteDevelopmentService - Vonixu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative pt-24">
        <WebsiteDevelopmentService />
      </main>
    </>
  );
};

export default websiteDevelopmentService;
